version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Watcherfile
    volumes: 
      - ./:/go/src/github.com/briansimoni/stereodose/
    working_dir: /go/src/github.com/briansimoni/stereodose/
    ports: 
      - "4000:4000"
    depends_on: 
      - db
    environment:
      - STEREODOSE_CLIENT_ID=${STEREODOSE_CLIENT_ID}
      - STEREODOSE_CLIENT_SECRET=${STEREODOSE_CLIENT_SECRET}
      - STEREODOSE_REDIRECT_URL=${STEREODOSE_REDIRECT_URL}
      - STEREODOSE_ENCRYPTION_KEY=${STEREODOSE_ENCRYPTION_KEY}
      - STEREODOSE_AUTH_KEY=${STEREODOSE_AUTH_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: watcher


  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stereodose
      POSTGRES_PASSWORD: development