# For development purposes only.

version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Watcherfile
    volumes: 
      - ./:/go/src/github.com/briansimoni/stereodose/
    working_dir: /go/src/github.com/briansimoni/stereodose/
    ports: 
      - "4000:4000"
      - "40000:40000" # dlv debug server port
    depends_on: 
      - db
    security_opt:
      - seccomp:unconfined
    environment:
      - STEREODOSE_CLIENT_ID=${STEREODOSE_CLIENT_ID}
      - STEREODOSE_CLIENT_SECRET=${STEREODOSE_CLIENT_SECRET}
      - STEREODOSE_REDIRECT_URL=${STEREODOSE_REDIRECT_URL}
      - STEREODOSE_ENCRYPTION_KEY=${STEREODOSE_ENCRYPTION_KEY}
      - STEREODOSE_AUTH_KEY=${STEREODOSE_AUTH_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: modd


  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stereodose
      POSTGRES_PASSWORD: development