version: "3"

services:
  app:
    build: .
    volumes: 
      - .:/go/src/github/com/briansimoni/stereodose/
    working_dir: /go/src/github/com/briansimoni/stereodose/
    ports: 
      - "3000:3000"
    depends_on: 
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: development